import string, random


def token_generator(size=8, chars=string.digits + string.ascii_letters):
    """
    Returns autogenerated token
    """
    return ''.join(random.choice(chars) for _ in range(size))


def create_short_url(instance):
    """
    Saves unique token for every single instance
    """
    token = token_generator()
    instance_class = instance.__class__
    if instance_class.objects.filter(short_url=token).exists():
        return create_short_url(instance)
    return token
